### ISSUE TITLE
slow queries in crawler.tasks

### ISSUE THREAD

**Issue by monkeypants** [AusDTO/discoveryLayer#81]
this query took 10940 seconds

    select
        url, hash, protocol, "contentType",
        host, port, path, "lastFetchDateTime"
    from "webDocuments"
    where "fetchStatus" = 'downloaded'
        and url not in (
            select url
            from metadata_resource
        )
    ;

It could be rewritten to be faster, but even this query took 2207 seconds

    select count(*)
    from "webDocuments"
    where "fetchStatus" = 'downloaded';

And this one took 9187 seconds

    select count(*)
    from "webDocuments";

 probably needs better indexing. @nokout , any suggestions?

**Comment by maxious** [comment]
Counts are bad but in postgres there is a "reltuples" value which is updated on vacuum (which happens automatically on a regular basis or you can do manually) https://wiki.postgresql.org/wiki/Slow_Counting
Also for your fetchStatus based count, there is https://wiki.postgresql.org/wiki/Index-only_scans

**Comment by nokout** [comment]
OK, as alex put above counts do suck, but Chris confirmed that that is not a real problem atm. Also confirmed that his code apends a limit variable on the query. I did up the working memory from 4MB to 16MB no other changes made.

So the test query I ran is...

```
    select url, hash, protocol, "contentType",
        host, port, path, "lastFetchDateTime"
    from "webDocuments"
    where "fetchStatus" = 'downloaded'
        and url not in (
            select url
            from metadata_resource
        )
    LIMIT 1000;
```
Total query runtime: 489 ms.

Back to you @monkeypants ;-)

**Comment by monkeypants** [comment]
Confirmed, performance is fine if I use LIMIT.

It's the doctor's solution; "OK, so don't do that then".
